# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_bilibili.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_bilibili.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14hello_bilibili.proto\x12\x04test\"*\n\rHelloDeweiReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0fHelloDeweiReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xc1\x01\n\x10HelloTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x12\x32\n\x06number\x18\x04 \x03(\x0b\x32\".test.HelloTestRequest.NumberEntry\x1aP\n\x0bNumberEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.test.HelloTestRequestNumberValue:\x02\x38\x01\"K\n\x1bHelloTestRequestNumberValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tis_active\x18\x03 \x01(\x08\"\x13\n\x11HelloTestResponse2\x84\x01\n\x06\x42ibili\x12:\n\nHelloDewei\x12\x13.test.HelloDeweiReq\x1a\x15.test.HelloDeweiReply\"\x00\x12>\n\tHelloTest\x12\x16.test.HelloTestRequest\x1a\x17.test.HelloTestResponse\"\x00\x62\x06proto3'
)




_HELLODEWEIREQ = _descriptor.Descriptor(
  name='HelloDeweiReq',
  full_name='test.HelloDeweiReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloDeweiReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloDeweiReq.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=72,
)


_HELLODEWEIREPLY = _descriptor.Descriptor(
  name='HelloDeweiReply',
  full_name='test.HelloDeweiReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloDeweiReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=107,
)


_HELLOTESTREQUEST_NUMBERENTRY = _descriptor.Descriptor(
  name='NumberEntry',
  full_name='test.HelloTestRequest.NumberEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test.HelloTestRequest.NumberEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='test.HelloTestRequest.NumberEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=303,
)

_HELLOTESTREQUEST = _descriptor.Descriptor(
  name='HelloTestRequest',
  full_name='test.HelloTestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloTestRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloTestRequest.age', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='test.HelloTestRequest.data', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='test.HelloTestRequest.number', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HELLOTESTREQUEST_NUMBERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=303,
)


_HELLOTESTREQUESTNUMBERVALUE = _descriptor.Descriptor(
  name='HelloTestRequestNumberValue',
  full_name='test.HelloTestRequestNumberValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloTestRequestNumberValue.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloTestRequestNumberValue.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='test.HelloTestRequestNumberValue.is_active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=380,
)


_HELLOTESTRESPONSE = _descriptor.Descriptor(
  name='HelloTestResponse',
  full_name='test.HelloTestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=401,
)

_HELLOTESTREQUEST_NUMBERENTRY.fields_by_name['value'].message_type = _HELLOTESTREQUESTNUMBERVALUE
_HELLOTESTREQUEST_NUMBERENTRY.containing_type = _HELLOTESTREQUEST
_HELLOTESTREQUEST.fields_by_name['number'].message_type = _HELLOTESTREQUEST_NUMBERENTRY
DESCRIPTOR.message_types_by_name['HelloDeweiReq'] = _HELLODEWEIREQ
DESCRIPTOR.message_types_by_name['HelloDeweiReply'] = _HELLODEWEIREPLY
DESCRIPTOR.message_types_by_name['HelloTestRequest'] = _HELLOTESTREQUEST
DESCRIPTOR.message_types_by_name['HelloTestRequestNumberValue'] = _HELLOTESTREQUESTNUMBERVALUE
DESCRIPTOR.message_types_by_name['HelloTestResponse'] = _HELLOTESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloDeweiReq = _reflection.GeneratedProtocolMessageType('HelloDeweiReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLODEWEIREQ,
  '__module__' : 'hello_bilibili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeweiReq)
  })
_sym_db.RegisterMessage(HelloDeweiReq)

HelloDeweiReply = _reflection.GeneratedProtocolMessageType('HelloDeweiReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLODEWEIREPLY,
  '__module__' : 'hello_bilibili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeweiReply)
  })
_sym_db.RegisterMessage(HelloDeweiReply)

HelloTestRequest = _reflection.GeneratedProtocolMessageType('HelloTestRequest', (_message.Message,), {

  'NumberEntry' : _reflection.GeneratedProtocolMessageType('NumberEntry', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQUEST_NUMBERENTRY,
    '__module__' : 'hello_bilibili_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestRequest.NumberEntry)
    })
  ,
  'DESCRIPTOR' : _HELLOTESTREQUEST,
  '__module__' : 'hello_bilibili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestRequest)
  })
_sym_db.RegisterMessage(HelloTestRequest)
_sym_db.RegisterMessage(HelloTestRequest.NumberEntry)

HelloTestRequestNumberValue = _reflection.GeneratedProtocolMessageType('HelloTestRequestNumberValue', (_message.Message,), {
  'DESCRIPTOR' : _HELLOTESTREQUESTNUMBERVALUE,
  '__module__' : 'hello_bilibili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestRequestNumberValue)
  })
_sym_db.RegisterMessage(HelloTestRequestNumberValue)

HelloTestResponse = _reflection.GeneratedProtocolMessageType('HelloTestResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOTESTRESPONSE,
  '__module__' : 'hello_bilibili_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestResponse)
  })
_sym_db.RegisterMessage(HelloTestResponse)


_HELLOTESTREQUEST_NUMBERENTRY._options = None

_BIBILI = _descriptor.ServiceDescriptor(
  name='Bibili',
  full_name='test.Bibili',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=536,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloDewei',
    full_name='test.Bibili.HelloDewei',
    index=0,
    containing_service=None,
    input_type=_HELLODEWEIREQ,
    output_type=_HELLODEWEIREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HelloTest',
    full_name='test.Bibili.HelloTest',
    index=1,
    containing_service=None,
    input_type=_HELLOTESTREQUEST,
    output_type=_HELLOTESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIBILI)

DESCRIPTOR.services_by_name['Bibili'] = _BIBILI

# @@protoc_insertion_point(module_scope)
