/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test_c.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test_c.pb-c.h"
void   test_c__hello_request__init
                     (TestC__HelloRequest         *message)
{
  static const TestC__HelloRequest init_value = TEST_C__HELLO_REQUEST__INIT;
  *message = init_value;
}
size_t test_c__hello_request__get_packed_size
                     (const TestC__HelloRequest *message)
{
  assert(message->base.descriptor == &test_c__hello_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test_c__hello_request__pack
                     (const TestC__HelloRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test_c__hello_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test_c__hello_request__pack_to_buffer
                     (const TestC__HelloRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test_c__hello_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TestC__HelloRequest *
       test_c__hello_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TestC__HelloRequest *)
     protobuf_c_message_unpack (&test_c__hello_request__descriptor,
                                allocator, len, data);
}
void   test_c__hello_request__free_unpacked
                     (TestC__HelloRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test_c__hello_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test_c__hello_reply__init
                     (TestC__HelloReply         *message)
{
  static const TestC__HelloReply init_value = TEST_C__HELLO_REPLY__INIT;
  *message = init_value;
}
size_t test_c__hello_reply__get_packed_size
                     (const TestC__HelloReply *message)
{
  assert(message->base.descriptor == &test_c__hello_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test_c__hello_reply__pack
                     (const TestC__HelloReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test_c__hello_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test_c__hello_reply__pack_to_buffer
                     (const TestC__HelloReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test_c__hello_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TestC__HelloReply *
       test_c__hello_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TestC__HelloReply *)
     protobuf_c_message_unpack (&test_c__hello_reply__descriptor,
                                allocator, len, data);
}
void   test_c__hello_reply__free_unpacked
                     (TestC__HelloReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test_c__hello_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor test_c__hello_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TestC__HelloRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test_c__hello_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange test_c__hello_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test_c__hello_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test_c.HelloRequest",
  "HelloRequest",
  "TestC__HelloRequest",
  "test_c",
  sizeof(TestC__HelloRequest),
  1,
  test_c__hello_request__field_descriptors,
  test_c__hello_request__field_indices_by_name,
  1,  test_c__hello_request__number_ranges,
  (ProtobufCMessageInit) test_c__hello_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test_c__hello_reply__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TestC__HelloReply, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test_c__hello_reply__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange test_c__hello_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test_c__hello_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test_c.HelloReply",
  "HelloReply",
  "TestC__HelloReply",
  "test_c",
  sizeof(TestC__HelloReply),
  1,
  test_c__hello_reply__field_descriptors,
  test_c__hello_reply__field_indices_by_name,
  1,  test_c__hello_reply__number_ranges,
  (ProtobufCMessageInit) test_c__hello_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor test_c__greeter__method_descriptors[1] =
{
  { "MyTestFirst", &test_c__hello_request__descriptor, &test_c__hello_reply__descriptor },
};
const unsigned test_c__greeter__method_indices_by_name[] = {
  0         /* MyTestFirst */
};
const ProtobufCServiceDescriptor test_c__greeter__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "test_c.Greeter",
  "Greeter",
  "TestC__Greeter",
  "test_c",
  1,
  test_c__greeter__method_descriptors,
  test_c__greeter__method_indices_by_name
};
void test_c__greeter__my_test_first(ProtobufCService *service,
                                    const TestC__HelloRequest *input,
                                    TestC__HelloReply_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &test_c__greeter__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void test_c__greeter__init (TestC__Greeter_Service *service,
                            TestC__Greeter_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &test_c__greeter__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
